/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.assyifacake.views.MenuUtama;

import com.assyifacake.controllers.MenuUtama.MenuUtamaController;
import com.assyifacake.views.Produk.AturProdukInternalView;
import com.assyifacake.views.AturAkun.AturAkunView;
import com.assyifacake.views.DaftarPembeli.DaftarPembeliInternalView;
import com.assyifacake.views.LaporanPenjualan.LaporanPenjualanInternalView;
import com.assyifacake.views.Produk.LihatProdukInternalView;
import com.assyifacake.views.Resep.AturResepInternalView;
import com.assyifacake.views.Transaksi.BuatTransaksiInternalView;
import com.assyifacake.views.Transaksi.DetailTransaksiInternalView;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author hp
 */
public class MenuUtamaView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */

    public JLabel getUsernameTF() {
        return usernameTF;
    }

    public JPopupMenu getPopupTransaksi() {
        return popupTransaksi;
    }

    public JPopupMenu getPopupUser() {
        return popupUser;
    }

    public JMenuItem getMenuItem() {
        return menuItem;
    }

    public MenuUtamaController getController() {
        return controller;
    }

    public JLabel getDaftarPembeliNavTF() {
        return daftarPembeliNavTF;
    }

    public JLabel getIcUserLB() {
        return icUserLB;
    }

    public JDesktopPane getPanel() {
        return panel;
    }

    public JLabel getProdukNavTF() {
        return produkNavTF;
    }

    public JLabel getTransaksiNavTF() {
        return transaksiNavTF;
    }
    
    private final JPopupMenu popupProduk = new JPopupMenu();
    private final JPopupMenu popupTransaksi = new JPopupMenu();
    private final JPopupMenu popupUser = new JPopupMenu();
    private JMenuItem menuItem = null;
    private MenuUtamaController controller;
    
    public MenuUtamaView() {
        this.setUndecorated(true);
        initComponents();
        controller = new MenuUtamaController(this);
        this.controller.startAwal();
        
       
        
//        DetailProdukInternalView dpiv = new DetailProdukInternalView();
//        panel.add(dpiv);
//        Dimension desktopSize = panel.getSize();
//        Dimension jInternalFrameSize = dpiv.getSize();
//        dpiv.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
//        (desktopSize.height- jInternalFrameSize.height)/2);
//        dpiv.setVisible(true);

        
//        DetailResepInternalView driv = new DetailResepInternalView();
//        panel.add(driv);
//        Dimension desktopSize = panel.getSize();
//        Dimension jInternalFrameSize = driv.getSize();
//        driv.setLocation((desktopSize.width - jInternalFrameSize.width)/2,
//        (desktopSize.height- jInternalFrameSize.height)/2);
//        driv.setVisible(true);

        


//        // user image
//        JLabel userIc;
//        setSize(40, 40);
//        setLayout(null);
//        setDefaultCloseOperation(EXIT_ON_CLOSE);
//        ImageIcon imgUserIc = new ImageIcon("src/main/java/com/assyifacake/resources/img/ic_user.png");
//        
//        userIc = new JLabel("", imgUserIc, JLabel.CENTER);
//        userIc.setBounds(700,10,40,40);
//        add(userIc);
        
        // bg image
        JLabel background;
        setSize(770, 540);
        setLayout(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        ImageIcon img = new ImageIcon(getClass().getResource("/img/bg_dark.png"));
        
        background = new JLabel("", img, JLabel.CENTER);
        background.setBounds(0,0,770,540);
        add(background);
        setVisible(true);
        
        // Call Our Method
        createPopupProduk();
        createPopupTransaksi();
        createPopupUser();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        panel = new javax.swing.JDesktopPane();
        produkNavTF = new javax.swing.JLabel();
        transaksiNavTF = new javax.swing.JLabel();
        daftarPembeliNavTF = new javax.swing.JLabel();
        usernameTF = new javax.swing.JLabel();
        icUserLB = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        laporanPenjualaniNavTF = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel.setBorder(null);
        panel.setPreferredSize(new java.awt.Dimension(778, 480));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        produkNavTF.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        produkNavTF.setForeground(new java.awt.Color(255, 255, 255));
        produkNavTF.setText("Produk");
        produkNavTF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        produkNavTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produkNavTFMouseClicked(evt);
            }
        });

        transaksiNavTF.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        transaksiNavTF.setForeground(new java.awt.Color(255, 255, 255));
        transaksiNavTF.setText("Transaksi");
        transaksiNavTF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaksiNavTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiNavTFMouseClicked(evt);
            }
        });

        daftarPembeliNavTF.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        daftarPembeliNavTF.setForeground(new java.awt.Color(255, 255, 255));
        daftarPembeliNavTF.setText("Daftar Pembeli");
        daftarPembeliNavTF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        daftarPembeliNavTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarPembeliNavTFMouseClicked(evt);
            }
        });

        usernameTF.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        usernameTF.setForeground(new java.awt.Color(255, 255, 255));
        usernameTF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameTF.setText("Username");
        usernameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usernameTF.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        usernameTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameTFMouseClicked(evt);
            }
        });

        icUserLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ic_user.png"))); // NOI18N
        icUserLB.setText("jLabel5");
        icUserLB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icUserLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icUserLBMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close-button.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimize-button.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel1.setText("Program Assyifa Cakes");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_homemade-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        laporanPenjualaniNavTF.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        laporanPenjualaniNavTF.setForeground(new java.awt.Color(255, 255, 255));
        laporanPenjualaniNavTF.setText("Laporan Penjualan");
        laporanPenjualaniNavTF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporanPenjualaniNavTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanPenjualaniNavTFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, 770, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(produkNavTF)
                .addGap(25, 25, 25)
                .addComponent(transaksiNavTF)
                .addGap(25, 25, 25)
                .addComponent(daftarPembeliNavTF)
                .addGap(25, 25, 25)
                .addComponent(laporanPenjualaniNavTF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(icUserLB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(produkNavTF)
                    .addComponent(transaksiNavTF)
                    .addComponent(daftarPembeliNavTF)
                    .addComponent(usernameTF)
                    .addComponent(icUserLB)
                    .addComponent(laporanPenjualaniNavTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTFMouseClicked
        // TODO add your handling code here:
        // Show Popup Menu
        popupUser.show(this, 600, 80);
    }//GEN-LAST:event_usernameTFMouseClicked

    private void icUserLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icUserLBMouseClicked
        // TODO add your handling code here:
        // Show Popup Menu
        popupUser.show(this, 600, 80);
    }//GEN-LAST:event_icUserLBMouseClicked

    private void produkNavTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produkNavTFMouseClicked
        // TODO add your handling code here:
        // Show Popup Menu
        popupProduk.show(this, 30, 80);
    }//GEN-LAST:event_produkNavTFMouseClicked

    private void transaksiNavTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiNavTFMouseClicked
        // TODO add your handling code here:
        // Show Popup Menu
        popupTransaksi.show(this, 130, 80);
    }//GEN-LAST:event_transaksiNavTFMouseClicked

    private void daftarPembeliNavTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarPembeliNavTFMouseClicked
        DaftarPembeliInternalView pembeli = new DaftarPembeliInternalView();
        controller.tampilKePanel(pembeli);  
    }//GEN-LAST:event_daftarPembeliNavTFMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x, y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void laporanPenjualaniNavTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPenjualaniNavTFMouseClicked
        // TODO add your handling code here:
        LaporanPenjualanInternalView laporan = new LaporanPenjualanInternalView();
        controller.tampilKePanel(laporan);
    }//GEN-LAST:event_laporanPenjualaniNavTFMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuUtamaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuUtamaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuUtamaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuUtamaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new MenuUtamaView().setVisible(true);
////            }
////        });
//        new MenuUtamaView().setVisible(true);
//    }
    
    // =================================================Menu Popup Produk ========================================================
    
    // Create Menu Method
    private void createPopupProduk() {
        // Create File Menu
        menuItem = new JMenuItem(
                "Lihat Produk",
                new ImageIcon(getClass().getResource("/img/ic_view.png")
        ));
        // Apply Desc
        menuItem.getAccessibleContext().setAccessibleDescription("Lihat Produk");
        menuItem.setFont(new Font("Montserrat", Font.PLAIN, 18));
        // Create an Action Listener
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                 LihatProdukInternalView lpiv = new LihatProdukInternalView();
                 controller.tampilKePanel(lpiv);
                
                
            }
        });
        // Add Menu Item Into Popup Menu
        popupProduk.add(menuItem);

        // Add another menu item to popup menu
        menuItem = new JMenuItem(
                "Atur Produk",
                new ImageIcon(getClass().getResource("/img/ic_settings.png")
        ));
        // Apply Desc
        menuItem.getAccessibleContext().setAccessibleDescription("Atur Produk");
        menuItem.setFont(new Font("Montserrat", Font.PLAIN, 18));
        // Create an Action Listener
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                    
                    AturProdukInternalView apiv = new AturProdukInternalView();
                    controller.tampilKePanel(apiv);
                
                
                }
            }

            );
        // Add Menu Item Into Popup Menu
            popupProduk.add (menuItem);
            
            
            // Add another menu item to popup menu
        menuItem = new JMenuItem(
                "Atur Resep",
                new ImageIcon(getClass().getResource("/img/ic_settings.png")
        ));
        // Apply Desc
        menuItem.getAccessibleContext().setAccessibleDescription("Atur Resep");
        menuItem.setFont(new Font("Montserrat", Font.PLAIN, 18));
        // Create an Action Listener
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                    
                AturResepInternalView ariv = new AturResepInternalView();
                controller.tampilKePanel(ariv);    
                }
            }

            );
        // Add Menu Item Into Popup Menu
            popupProduk.add (menuItem);
        }
    
    // =================================================Menu Popup Transaksi ========================================================
    
    // Create Menu Method
    private void createPopupTransaksi() {
        // Create File Menu
        menuItem = new JMenuItem(
                "Lihat Transaksi",
                new ImageIcon(getClass().getResource("/img/ic_view.png")
        ));
        // Apply Desc
        menuItem.getAccessibleContext().setAccessibleDescription("Lihat Transaksi");
        menuItem.setFont(new Font("Montserrat", Font.PLAIN, 18));
        // Create an Action Listener
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                DetailTransaksiInternalView ltiv = new DetailTransaksiInternalView();
                controller.tampilKePanel(ltiv);
                
            }
        });
        // Add Menu Item Into Popup Menu
        popupTransaksi.add(menuItem);

        // Add another menu item to popup menu
        menuItem = new JMenuItem(
                "Buat Transaksi",
                new ImageIcon(getClass().getResource("/img/ic_plus.png")
        ));
        // Apply Desc
        menuItem.getAccessibleContext().setAccessibleDescription("Buat Transaksi");
        menuItem.setFont(new Font("Montserrat", Font.PLAIN, 18));
        // Create an Action Listener
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                BuatTransaksiInternalView ativ = new BuatTransaksiInternalView();
                controller.tampilKePanel(ativ);                 
            
                }
            }

            );
        // Add Menu Item Into Popup Menu
            popupTransaksi.add (menuItem);
            
        }
    
    // =================================================Menu Popup User ========================================================
    
    // Create Menu Method
    private void createPopupUser() {
        // Create File Menu
        menuItem = new JMenuItem(
                "Atur Akun",
                new ImageIcon(getClass().getResource("/img/ic_settings.png")
        ));
        // Apply Desc
        menuItem.getAccessibleContext().setAccessibleDescription("Atur Akun");
        menuItem.setFont(new Font("Montserrat", Font.PLAIN, 18));
        // Create an Action Listener
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                controller.tampilKePanel(new AturAkunView());
                
            }
        });
        // Add Menu Item Into Popup Menu
        popupUser.add(menuItem);
        
        // Create File Menu
        menuItem = new JMenuItem(
                "Logout",
                new ImageIcon(getClass().getResource("/img/ic_logout.png")
        ));
        // Apply Desc
        menuItem.getAccessibleContext().setAccessibleDescription("Logout");
        menuItem.setFont(new Font("Montserrat", Font.PLAIN, 18));
        // Create an Action Listener
        menuItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                controller.logout();
                
            }
        });
        // Add Menu Item Into Popup Menu
        popupUser.add(menuItem);
            
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daftarPembeliNavTF;
    private javax.swing.JLabel icUserLB;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel laporanPenjualaniNavTF;
    private javax.swing.JDesktopPane panel;
    private javax.swing.JLabel produkNavTF;
    private javax.swing.JLabel transaksiNavTF;
    private javax.swing.JLabel usernameTF;
    // End of variables declaration//GEN-END:variables
}
